# Generated by Django 4.1.4 on 2022-12-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_alter_task_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', 'deadline']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='progres',
            new_name='progress',
        ),
    ]
