# Generated by Django 4.1.4 on 2022-12-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_alter_task_options_rename_datetime_task_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='progress',
            new_name='is_done',
        ),
    ]
